using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace clickerGame
{
    public class news
    {
        public string[] newsList =
        {
            "Stupid person susbscibed to the worst news site today!",
            "Elon Musk buys Apple inc. for 69 Billion dollars!",
            "Tesla shares plumit as giant astroid crashes into Earth!",
            "Obama passes bill that prohibits breathing of oxygen in the US!",
            "North Korea leader seen walking on water yesterday!",
            "AUGHHHHGHGHHHHHHHH",
            "A break in happened yesterday and reports say that it was only nuclear launch codes!",
            "Console.WriteLine('I HATE YOU')",
            "Did you know that this 'game' was made in C#?",
            "Don't you have homework or something?",
            "Major eruption of small vocano off the coast of Liechtenstein!",
            "Year 2066 predicted to have dinosaurs come back!",
            "Andrew Tate found dead in Romania after fight with James Charles!",
            "Sex 2 Dropping in 2 months in a Kmart near you!",
            "Sponsored by Red Ball!",
            "Spider Man caught selling meth in a shoebox!",
            "LeBron James shot dead in da hood by a thug hunter!",
            "The thug shaker was removed in the latest patch of Earth!",
            "Man gets harassed in public for wearing a My Hero Academia hoodie!",
            "Jesus found guilty of 11 charges of tax fruad!",
            "Kanye West drops new single!",
            "Minecraft is removing any items that can cause damage in real life. Every item is being removed!",
            "Lead found in a water source near you!",
            "Fox news is shutting down after filing for bankruptency yesterday!",
            "Twitter is now home to 4 billion users and growing expenatualy by the second!",
            "Roblox is facing lawsuits after child claims their parent owns the company!",
            "You do not need dental care!",
            "Did you know that if you die in Germany, you die in real life?",
            "Plane tickets cost more than rubber bands!",
            "There is a rubber band comapny. I think they suck and should stop!",
            "I take no responsibility for damage of property!",
            "Lankybox found dead in his house after making a video on the 'Amogus came to my house at 3AM challenge' He was brutaly stabbed!",
            "Existing is illigal now!",
            "WOOOO im crazy in the head!",
            "I dont get paid enough, now wheres my coffee!",
            "*uwu notices how you DONT HAVE A LIFE*",
            "I AM IN YOUR WALLS!",
            "I'm outta ideas!",
            "LeBron played football for Poland tomorrow!",
            "Popular consparicy that the earth is flat is FALSE!",
            "the news is a string array that gets randomly picked using the random fuction and gets displayed",
            "Did you know, you can type ':3' in a calculator?",
            "Im so cool frfr ong",
            "Donald Duck found guilty of 3 charges of homocide and 6 charges of 3rd degree murder!",
            "Singer Harry Styles is now dating James Charles in the brand new TV show!",
            "Triangles have three sides!",
            "230 - 220 * 1 / 2 = 5!",
            "GAYming",
            "Notch buys Microsoft for 9.8 dollars!",
            "Lead singer of band Led Zeppelin found [redacted] in [redacted]!",
            "'You can get free Robux from cool websites' - Winsted Churchill, 1634",
            "Discord chats and calls are recorded and will be made public for people to see later this year!",
            "Leafy is here found guilty of 4 charges of assult with attempt to kill",
            "Donald Trump makes debut album called 'Great America'",
            "uwu owo :3 arf HELP ME PLS",
            "\"Balls\" - Stephen Hawking, 2039",
            "A good sleep schedule is necessary for health",
            "Not playing the game won't kill you",
            "Rubber bands shown to cause cancer in sea turtles",
            "BREAKING NEWS: We still don't know how to fix it",
            "90% of people didn't kill the tenth person",
            "Physicists find free energy bug due to floating point precision error",
            "BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion leads to BREAKING NEWS: Recursion broke, sorry",
            "Band member of REM found dead after dying!",
            "Its all in your head! Its all in your head! Its all in your head! Its all in your head! Its all in your head! Its all in your head! Its all in your head! Its all in your head! Its all in your head!",
            "Goku found dead in Detroit!",
            "98% of people say that this is statisticaly correct!",
            "\"We're making it out of the hood with this one\" - A random person, before taking their hoodie off",
            "iPhone 70 ultra max fold 5G plus waterproof due to come out later this year!",
            "Historians find the 11th Commandment to be \"Thou shalt be ballin'\"",
            "99% of people think that they are Batman!",
            "Obama finally reveals his last name! Find out more at [HYPERLINK BLOCKED]",
            "GTA VI predicted to run at a whopping 6 FPS on a 3090Ti!",
            "Amongus found alive in space smoking weed with Tenatious D",
            "m kybrd isbrkng apar pleae hlp",
            "weeeeeeeeeee!",
            "Sans bossfight NERFED after cat saying it was too difficult!",
            "Cows now produce 10x more milk then sheep!",
            "\"I don't know what a party is, is that like a thing teenagers go to?\" - A politician and definitely not three very intelligent (and handsome) octopodes in a trench coat",
            "Man lauches rubber band into space! \"My fingers hurt\"",
            "Listen to \"Southeast Border\" in Spotify!",
            "Pink Floyd recording new album \"Light side of the Sun\"",
            "Happy international rubber band day!",
            "Cats are cool!",
            "WHAT THE HELL IS A CHUNGUS!",
            "People said to land on Mars by 2024 and live there by 2025!",
            "Historians find the 12th Commandment to be \"Thou shalt not have a skill issue\"",
            "Schools due to start the next week. Studies show that depression spiked in students this week!",
            "Man dies of kidney failure after drinking too many Monsters for the flavour \"I drink these as much as normal sodas\" were his last words!",
            "Tax frauds cause by Osama bin Laden have caused mayor water leaks in Obamas personal bathroom!",
            "The cake is a lie!",
            "Circles crowned the best shape in this years poll!",
            "Led Zeppelin? nah, Graphite Blimp!",
            "Geometrical Dominator reached charts number 1 last month!",
            "Discord forces light mode on users, starting next week! AUGHHHH",
            "The last message was false!",
            "This message is false!",
            "Look behind you!",
            "Rubber bands gets lost when you fling them. Thats why we invented \"Track'a'Band\" It will show every rubber band in existence!\nThe servers are currently broken as too many requests!",
            "A recent poll concludes that 98.3% of people usualy partake in polls!",
            "Thead.Sleep(double.MaxValue)",
            "This game involves clicking!",
            "Studies show that a lack of sleep results in a 100% mortality chance. This paper was published by the Univercity of Sleep!",
            "Rubber bands are predicted to crash the economy, experts beleve this!",
            "The sun is a Sun and stars are Planets. Galaxies cannot be viewed by the naked eye! The earth is a star, relitive to the Adromeda Galaxy!",
            "False infomation up ahead!",
            "Jupiter actully has a belt, but you can only see it using X-ray!",
            "Windows OS can actully function without System32!",
            "Most facts here are simply made up. I assume no damage to property!",
            "China's largest export is actully Lego bricks!",
            "Chile mesured a export value of 2.6 Billions dollars of rice last year!",
            "Team Cherry anounces new game \"Solid Day\" due to hit shelves in 2024!",
            "K2 is actully higher that Mt. Everist because Mt. Eveist does not exist!",
            "Why does the the birds sit outside? Read this twice!",
            "The The members found guilty of charges of tax fruad!",
            "It is a great day. Don't you think so?",
            "Studies conclude that 100% of people who drink water die!",
            "*MATH GAG GOES HERE*",
            "Say \"yes\", but replace the \"yes\" with \"Amongus\"!",
            "You have produced more than one rubber band since the last second!",
            "Birthday party, cheesecake, jelly bean, boom! You symbiotic, patriotic, slam book neck, right? Right\nGuess what song this is from!",
            "do do dooooo dooo doooo it starts with one! ",
            "Wll i know, time is a valuable thing",
            "Watch it fly by as the pendulm swings",
            "Don't you have a assignment due later?",
            "Microphone companies created microphones to crash the stock market! Search up \"fake news\" to find out more!",
            "r/softwaregore",
            "R/foundthemobileuser",
            "You smell, take a shower please!",
            "Google plans to discontinue the Google search engine, for a superior competetor, Microsoft Bing!",
            "My spelling sucks!",
            "return;",
            "while(true)",
            "Lua indexes start at 1 not 0. It is a sin!"

        };
    }
    public class codes
    {
        public string[,] secretCodes = new string[,]
        {
            {"69420", "false"},
            {"ILOVETHISGAME", "false"},
            {"false", "false"},
            {"rubberband", "false"}
        };
    }
}
